"""Quarterly recalibration for BOTH Massachusetts models -- the single entry point.

WHY THIS EXISTS, specifically. The RI project's `quarterly_recalibration.py`
was written because a human had to remember to run things, and forgot. MA has
now demonstrated the same failure with a sharper edge: on 2026-08-10 the agent
identifier changed from `agent_profile_id` to `mls_agent_id`; the change landed
in both MA `data.py` files and nothing re-ran the scoring. For three weeks both
shipped MA spreadsheets carried the retired UUID in column 1 while every RI
output carried the MLS id, so **any join between an MA file and an RI file
matched zero rows** -- and separately, 1,084 agents carried a "below-average
listing activity" explanation that a 2026-08-11 source fix had already
suppressed. Neither defect was visible in any number a person would eyeball:
the roster was the right size, the tiers looked sensible, the top-10 was
plausible. The model was fine the whole time. The join key and 1,084 sentences
were not.

So this script adds no statistical method. It makes the existing one run on a
cadence, refuse to ship output that fails its checks, and leave a per-quarter
record of what the calibration did.

HOW IT DIFFERS FROM THE RI WRAPPER, and why -- three deliberate divergences:

  1. IT RUNS BOTH MODELS. RI's wrapper drives the Leave model alone. In MA the
     Leave and Sales outputs are scored off the same snapshot, cover the same
     27,019-agent roster, and went stale together. Driving them from one entry
     point is what makes the cross-model check below possible at all.

  2. THERE IS NO MIRROR STEP, because MA has nothing to mirror to -- there is
     one copy of each model, no `Final_Model/`, no repo-root duplicate. RI's
     step 4 is replaced by CROSS-MODEL CONSISTENCY (see check_cross_model):
     the two outputs must agree on key column, roster and snapshot. That check
     is not a like-for-like substitute; it is the check that would have caught
     the actual 2026-08 failure, which no tier-distribution gate could.

  3. IT RE-DERIVES THE OFFICE-PAIR CATALOGUE rather than refusing to proceed
     until a human classifies new clusters. RI's catalogue is hand-curated and
     web-verified, so an unknown cluster there is a genuine open question and
     the run must stop. MA's is GENERATED by `derive_ma_office_pairs.py` and no
     MA pair has ever been web-verified -- Tier B auto-gates any >=5-mover
     cluster on the unverified-but-conservative rule documented in that script.
     Stopping the run would therefore be theatre: there is no verification step
     for it to wait on. Instead the catalogue is regenerated (removing the
     "someone forgot to re-run derive" failure mode entirely) and every NEW
     Tier B cluster is surfaced, counted, and written into the log, so
     auto-gated recodes become visible per quarter instead of silent. Pass
     `--strict-clusters` to make new clusters abort the run if you would rather
     review them first.

WHAT "QUARTERLY" MEANS HERE, as in RI: due-ness is decided by the DATA, not the
calendar. A run is due when the source file holds a snapshot quarter newer than
the last recorded run used, or when the source file itself has been swapped --
that second trigger is exactly what the 2026-08-10 identifier change looked
like from the outside, and is the trigger that would have caught it. On an
unchanged panel the default is to exit cleanly and do nothing, so this is safe
to schedule more often than quarterly:

    schtasks /create /tn "MA quarterly recalibration" /sc monthly ^
      /tr "cmd /c ..\\Likelihood_to_Leave_Algorithm\\.venv\\Scripts\\python.exe ^
           C:\\Users\\olive\\RA_Algorithms_White\\MA\\quarterly_recalibration.py" /st 06:00

STAGING. Both models are scored into a temporary directory and only promoted
into the model folders once every check passes. A failing run therefore leaves
the previously shipped files untouched rather than overwriting them with output
nobody has looked at. This is how RI's "failures block the mirror" property is
preserved without a mirror.

SUBPROCESSES, not imports. Each model runs as its own interpreter. Two reasons,
both load-bearing: `MA/Likelihood_to_Leave/` and `MA/Forecasted_Sales/` each
contain a module named `data` and one named `score_agents`, so they cannot both
be imported into one process; and the office-pair catalogue is regenerated in
step 1, which would have no effect on an already-imported `data` module. Python
puts a script's own directory on `sys.path`, so running each scorer by absolute
path with `cwd` set to the staging directory resolves its imports correctly
while its relative OUTPUT_PATH lands in staging.

WHAT THIS DOES NOT DO.

- It does not re-key anything. If a future identifier change lands, the Leave
  model can be rescored (its pipeline never sorts on the agent key, so a rerun
  is score-neutral -- verified 2026-08-30, max |diff| 0.0 across 27,019 agents)
  but the Sales model must NOT be, because it sorts on the key and both its
  learners subsample by row order. Re-key that one by crosswalk join. See
  MA/README.md.
- It does not run the 6m/12m horizons. MA has no `train_multi_horizon.py`, and
  per the RI 2026-08-25 measurement the 3-month ranking is what ships.
- It does not touch `MULT_CUT_POINTS`, rebuild the PDF report, or promote any
  Tier B office pair into Tier A. Promotion needs web verification and is a
  human call, recorded in `derive_ma_office_pairs.py`.
"""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

MA_DIR = Path(__file__).resolve().parent
LEAVE_DIR = MA_DIR / "Likelihood_to_Leave"
SALES_DIR = MA_DIR / "Forecasted_Sales"

STATE_PATH = MA_DIR / "recalibration_state.json"
LOG_PATH = MA_DIR / "recalibration_log.csv"

SCORES_FILENAME = "current_agent_risk_scores.csv"
FORECAST_FILENAME = "current_agent_sales_forecast.csv"
META_FILENAME = "score_meta.json"
CANDIDATES_FILENAME = "ma_office_pair_candidates.csv"

# --- Output check thresholds --------------------------------------------
#
# Deliberately NOT the tier shares quoted in MA/README.md (84.47 / 13.29 /
# 1.50 / 0.74). Those describe the 2026-07-01 roster; a gate hardcoded to a
# single quarter's distribution fires on every correct run once the roster
# legitimately moves, and a gate that always fires is a gate everyone ignores.
# So the checks are of three kinds: an exact structural invariant, wide
# absolute bounds only a broken run can violate, and a quarter-over-quarter
# comparison against this script's own recorded history.
TIER_4_SHARE_BOUNDS = (0.0025, 0.05)
TIER_1_MIN_SHARE = 0.40
BIAS_CORRECTION_WARN = (0.5, 1.5)   # MA has observed 0.726 to date
BIAS_CORRECTION_FAIL = (0.25, 4.0)
DRIFT_WARN_PCT_POINTS = 10.0

# The Sales output's contract, asserted rather than assumed -- MA/README.md
# claims schema parity with RI and that claim was false for three weeks.
CONFIDENCE_LEVELS = [50, 65, 70, 75, 80, 95]
EXPECTED_FORECAST_COLUMNS = 33

AGENT_KEY = "mls_agent_id"


class RecalibrationAborted(RuntimeError):
    """A guard or output check refused to let the run continue."""


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _banner(text: str) -> None:
    print()
    print("=" * 78)
    print(text)
    print("=" * 78)


def _run(script: Path, cwd: Path, label: str) -> None:
    """Run one model's scorer in its own interpreter. Output is streamed
    rather than captured -- these take minutes and a silent wrapper is
    indistinguishable from a hung one.
    """
    print(f"[run] {sys.executable}")
    print(f"[run] {script}  (cwd={cwd})")
    result = subprocess.run([sys.executable, "-u", str(script)], cwd=str(cwd))
    if result.returncode != 0:
        raise RecalibrationAborted(
            f"{label} exited {result.returncode}. Staged outputs left in {cwd}; nothing was promoted."
        )


# --- Step 0: is a run due? ----------------------------------------------


def _leave_constants() -> tuple[Path, str]:
    """DATA_PATH and MLS_CODE, read from the Leave model rather than
    duplicated here. Importing `data` in THIS process is safe because the
    parent never scores anything -- both scorers run as subprocesses, so the
    office-pair catalogue regenerated in step 1 is always the one they see.
    """
    if str(LEAVE_DIR) not in sys.path:
        sys.path.insert(0, str(LEAVE_DIR))
    import data as leave_data

    return leave_data.DATA_PATH, leave_data.MLS_CODE


def data_fingerprint(path: Path) -> dict:
    """Identity of the source file, so a file SWAP triggers a run even when
    the newest quarter in it is unchanged -- which is exactly what the
    2026-08-10 mls_agent_id swap looked like from the outside, and is the
    trigger that would have caught the three-week staleness this wrapper
    exists to prevent. Name + size, not a content hash: hashing 300MB on
    every due-check costs more than a tripwire `--force` can override.
    """
    stat = path.stat()
    return {"name": path.name, "size_bytes": stat.st_size}


def latest_data_quarter(path: Path, mls_code: str) -> pd.Timestamp:
    df = pd.read_csv(path, usecols=["mls_code", "snapshot_date"])
    df = df[df["mls_code"] == mls_code]
    return pd.to_datetime(df["snapshot_date"]).max()


def load_state() -> dict:
    if not STATE_PATH.exists():
        return {}
    return json.loads(STATE_PATH.read_text(encoding="utf-8"))


def check_due(state: dict, path: Path, mls_code: str) -> tuple[bool, str, pd.Timestamp]:
    quarter = latest_data_quarter(path, mls_code)
    fingerprint = data_fingerprint(path)

    if not state:
        return True, f"no previous run recorded ({STATE_PATH.name} absent)", quarter

    last_quarter = pd.Timestamp(state["data_quarter"])
    if quarter > last_quarter:
        return True, f"new quarter in the data: {quarter.date()} (last run used {last_quarter.date()})", quarter
    if state.get("data_file") != fingerprint:
        return True, (
            f"source file changed: {state.get('data_file')} -> {fingerprint} "
            f"(quarter unchanged at {quarter.date()})"
        ), quarter
    return False, (
        f"already recalibrated on quarter {quarter.date()} "
        f"(run {state.get('last_run_utc', 'unknown')}); nothing to do"
    ), quarter


# --- Step 1: office-pair catalogue --------------------------------------


def _load_candidates() -> pd.DataFrame:
    path = LEAVE_DIR / CANDIDATES_FILENAME
    if not path.exists():
        return pd.DataFrame(columns=["origin_office", "dest_office", "move_quarter", "n_movers"])
    return pd.read_csv(path)


def _instance_keys(cand: pd.DataFrame) -> set:
    if cand.empty:
        return set()
    return set(zip(cand["origin_office"], cand["dest_office"], cand["move_quarter"].astype(str)))


def refresh_office_pairs() -> tuple[pd.DataFrame, list[str]]:
    """Regenerate the catalogue and report what changed.

    Returns (new_clusters, notes). `new_clusters` are Tier B (pair, quarter)
    instances that were NOT in the previous catalogue -- i.e. mass moves this
    run will newly recode from "left" to "stayed" without any verification
    behind them. That is MA's documented weak point, so they are surfaced
    rather than absorbed silently.
    """
    _banner("STEP 1/4  Regenerate the office-pair catalogue, and report new mass-mover clusters")

    before_cand = _load_candidates()
    before_keys = _instance_keys(before_cand)
    catalogue = LEAVE_DIR / "rebrand_classifications.py"
    before_src = catalogue.read_text(encoding="utf-8") if catalogue.exists() else ""

    _run(LEAVE_DIR / "derive_ma_office_pairs.py", LEAVE_DIR, "derive_ma_office_pairs.py")

    after_cand = _load_candidates()
    after_keys = _instance_keys(after_cand)
    after_src = catalogue.read_text(encoding="utf-8") if catalogue.exists() else ""

    notes = []
    if after_src == before_src:
        notes.append("catalogue regenerated identically -- no office-pair change this run")
        print(f"\n[pairs] {notes[-1]}")
    else:
        notes.append("catalogue CHANGED this run (see the added/removed clusters below)")
        print(f"\n[pairs] {notes[-1]}")

    added_keys = after_keys - before_keys
    removed_keys = before_keys - after_keys
    added = after_cand[
        [k in added_keys for k in zip(after_cand["origin_office"], after_cand["dest_office"],
                                      after_cand["move_quarter"].astype(str))]
    ] if not after_cand.empty else after_cand

    print(f"[pairs] Tier B (pair, quarter) instances: {len(before_keys)} -> {len(after_keys)} "
          f"({len(added_keys)} added, {len(removed_keys)} removed)")

    if len(added_keys):
        cols = [c for c in ["origin_office", "origin_name", "dest_office", "dest_name",
                            "move_quarter", "n_movers", "name_containment"] if c in added.columns]
        print("\n[pairs] NEW unverified mass-mover clusters -- these will be recoded from 'left' to")
        print("        'stayed' on the cluster gate alone, with no web verification behind them:\n")
        with pd.option_context("display.max_colwidth", 30, "display.width", 200):
            print(added[cols].to_string(index=False))
        print("\n[pairs] Review these against the real world. If any is genuine competitor movement")
        print("        rather than a rebrand/acquisition, that is a label error in the model's favour")
        print("        and belongs in derive_ma_office_pairs.py as an exclusion.")
        notes.append(f"{len(added_keys)} new unverified Tier B cluster(s)")
    else:
        print("[pairs] no new mass-mover clusters")

    return added, notes


# --- Step 2: score both models into staging -----------------------------


def run_models(staging: Path) -> dict:
    _banner("STEP 2/4  Score both models into staging (Leave: retrain + refit Platt + rescore)")
    t0 = time.perf_counter()
    _run(LEAVE_DIR / "score_agents.py", staging, "Leave model scoring")
    leave_s = time.perf_counter() - t0

    meta_path = staging / META_FILENAME
    if not meta_path.exists():
        raise RecalibrationAborted(
            f"Leave scoring produced no {META_FILENAME} in {staging}. That file carries this quarter's "
            f"calibration constants and its absence means score_agents.py is older than this wrapper."
        )
    meta = json.loads(meta_path.read_text(encoding="utf-8"))

    _banner("STEP 2b/4  Score the Sales model off the same snapshot")
    t1 = time.perf_counter()
    _run(SALES_DIR / "score_agents.py", staging, "Sales model scoring")
    sales_s = time.perf_counter() - t1

    meta["leave_elapsed_s"] = round(leave_s, 1)
    meta["sales_elapsed_s"] = round(sales_s, 1)
    return meta


# --- Step 3: output checks ----------------------------------------------


def check_leave(scores: pd.DataFrame, meta: dict, state: dict) -> tuple[list[str], list[str]]:
    failures: list[str] = []
    warnings: list[str] = []

    shares = scores["risk_tier"].value_counts(normalize=True).sort_index()
    counts = scores["risk_tier"].value_counts().sort_index()
    print("[check] tier distribution:")
    for tier in (1, 2, 3, 4):
        print(f"          tier {tier}: {counts.get(tier, 0):6d} agents  ({shares.get(tier, 0.0):6.2%})")

    # (a) Structural invariant. Tiers are multiples of the bias-corrected base
    # rate, so every tier-N agent's risk_multiplier must sit inside tier N's
    # band -- true by construction on every correct run, however the roster
    # moves. This is what catches cutpoints and the multiplier denominator
    # being computed on different bases, which a distribution check catches
    # only by luck. (RI shipped exactly that bug on 2026-07-24: 1 Extra High
    # agent against a backtested ~1-2%.)
    bands = {1: (0.0, 1.0), 2: (1.0, 3.0), 3: (3.0, 6.0), 4: (6.0, float("inf"))}
    invariant_ok = True
    for tier, (lo, hi) in bands.items():
        rows = scores[scores["risk_tier"] == tier]
        if rows.empty:
            continue
        if rows["risk_multiplier"].min() < lo or rows["risk_multiplier"].max() >= hi:
            invariant_ok = False
            failures.append(
                f"tier {tier} multipliers run {rows['risk_multiplier'].min():.3f}-"
                f"{rows['risk_multiplier'].max():.3f}, outside the [{lo}, {hi}) band that defines the tier -- "
                f"cutpoints and risk_multiplier are not on the same basis"
            )
    if invariant_ok:
        print("[check] PASS  tier <-> risk_multiplier invariant holds in all four tiers")

    # (b) Absolute bounds -- wide on purpose; only a broken run trips these.
    tier4 = shares.get(4, 0.0)
    lo4, hi4 = TIER_4_SHARE_BOUNDS
    if not (lo4 <= tier4 <= hi4):
        failures.append(f"Extra High is {tier4:.3%} of the roster, outside the plausible {lo4:.2%}-{hi4:.0%} band")
    else:
        print(f"[check] PASS  Extra High share {tier4:.2%} within {lo4:.2%}-{hi4:.0%}")

    if shares.get(1, 0.0) < TIER_1_MIN_SHARE:
        failures.append(f"Low is only {shares.get(1, 0.0):.2%} of the roster (expected >= {TIER_1_MIN_SHARE:.0%})")
    if not (shares.get(1, 0) >= shares.get(2, 0) >= shares.get(3, 0)):
        warnings.append("tier shares are not decreasing across Low/Medium/High -- unusual, check before shipping")

    bias = meta["bias_correction"]
    if not (BIAS_CORRECTION_FAIL[0] <= bias <= BIAS_CORRECTION_FAIL[1]):
        failures.append(f"bias correction {bias:.4f}x is outside {BIAS_CORRECTION_FAIL} -- the calibrator is not usable")
    elif not (BIAS_CORRECTION_WARN[0] <= bias <= BIAS_CORRECTION_WARN[1]):
        warnings.append(
            f"bias correction {bias:.4f}x is outside the {BIAS_CORRECTION_WARN} range seen to date "
            f"(MA has observed 0.726) -- not necessarily wrong, but understand it before shipping"
        )
    else:
        print(f"[check] PASS  bias correction {bias:.4f}x within the range seen to date")

    # (c) Drift against this script's own history -- stays honest as the
    # roster legitimately moves, because its reference is last quarter rather
    # than a frozen backtest.
    prior = state.get("tier_shares") if state else None
    if not prior:
        print("[check] no previous run recorded -- drift check skipped (this run becomes the baseline)")
    else:
        for tier in (1, 2, 3, 4):
            before = prior.get(str(tier), 0.0) * 100
            now = shares.get(tier, 0.0) * 100
            move = now - before
            marker = "  <-- large move" if abs(move) > DRIFT_WARN_PCT_POINTS else ""
            print(f"[check] tier {tier}: {before:6.2f}% -> {now:6.2f}%  ({move:+.2f} pts){marker}")
            if abs(move) > DRIFT_WARN_PCT_POINTS:
                warnings.append(
                    f"tier {tier} share moved {move:+.2f} points since the last run "
                    f"({before:.2f}% -> {now:.2f}%) -- explain it before shipping"
                )

    return failures, warnings


def check_sales(forecast: pd.DataFrame) -> tuple[list[str], list[str]]:
    """Structural checks on the range forecast. Not accuracy -- accuracy needs
    a held-out backtest (`remeasure_accuracy.py`, not yet ported to MA). These
    assert the contract the spreadsheet's consumers rely on.
    """
    failures: list[str] = []
    warnings: list[str] = []

    if len(forecast.columns) != EXPECTED_FORECAST_COLUMNS:
        failures.append(
            f"forecast has {len(forecast.columns)} columns, expected {EXPECTED_FORECAST_COLUMNS} -- "
            f"MA/README.md claims schema parity with RI and downstream consumers rely on it"
        )
    else:
        print(f"[check] PASS  forecast schema is {EXPECTED_FORECAST_COLUMNS} columns")

    # Name the columns explicitly before touching any of them. Every value
    # check below indexes by column name, so a missing column would otherwise
    # raise KeyError out of this function -- which crashes the wrapper with a
    # traceback instead of taking the orderly "checks failed, nothing promoted"
    # path, and skips every remaining check including the cross-model one.
    # (Found by fault injection, 2026-08-30: dropping one column from the
    # forecast killed the run rather than failing it.)
    expected = []
    for label in ("volume", "units"):
        expected += [f"{label}_pct_zero", f"{label}_point_estimate"]
        for level in CONFIDENCE_LEVELS:
            expected += [f"{label}_min_{level}", f"{label}_max_{level}"]
    missing = [c for c in expected if c not in forecast.columns]
    if missing:
        failures.append(
            f"forecast is missing {len(missing)} required column(s): {', '.join(missing[:8])}"
            f"{' ...' if len(missing) > 8 else ''} -- value checks skipped, the file is not shippable"
        )
        return failures, warnings

    for label in ("volume", "units"):
        pz = forecast[f"{label}_pct_zero"]
        if pz.min() < 0 or pz.max() > 1:
            failures.append(f"{label}_pct_zero runs {pz.min()}-{pz.max()}, outside [0, 1] -- not a probability")

        point = forecast[f"{label}_point_estimate"]
        if (point < 0).any():
            failures.append(f"{(point < 0).sum()} negative {label}_point_estimate values")

        # Interval ordering, at every level. A crossed band (min > max) is the
        # signature of a conformal adjustment applied with the wrong sign, and
        # it is invisible in any summary statistic.
        for level in CONFIDENCE_LEVELS:
            lo = forecast[f"{label}_min_{level}"]
            hi = forecast[f"{label}_max_{level}"]
            crossed = int((lo > hi).sum())
            if crossed:
                failures.append(f"{crossed} rows have {label}_min_{level} > {label}_max_{level} -- crossed interval")

        # Nesting: a 95% band must contain the 50% band. Checked at the two
        # ends of the menu rather than all 15 pairs -- a violation anywhere is
        # almost always a violation here.
        widened = (forecast[f"{label}_min_95"] <= forecast[f"{label}_min_50"]) & \
                  (forecast[f"{label}_max_95"] >= forecast[f"{label}_max_50"])
        if not widened.all():
            warnings.append(
                f"{int((~widened).sum())} rows where the {label} 95% band does not contain the 50% band -- "
                f"expected after the realistic-floor snap on some rows, but check the count is small"
            )
    if not failures:
        print("[check] PASS  probabilities in range, no negative point estimates, no crossed intervals")
    return failures, warnings


def check_cross_model(scores: pd.DataFrame, forecast: pd.DataFrame) -> list[str]:
    """The check that would have caught the 2026-08 failure.

    Both files describe the same roster off the same snapshot and are joined
    downstream on the agent key. Nothing previously asserted that. When the
    identifier changed under both models and neither was rescored, every
    single-file check still passed -- the roster was the right size and the
    numbers were right. What was wrong only existed BETWEEN the files.
    """
    failures: list[str] = []

    if scores.columns[0] != AGENT_KEY:
        failures.append(f"Leave output is keyed on '{scores.columns[0]}', expected '{AGENT_KEY}'")
    if forecast.columns[0] != AGENT_KEY:
        failures.append(f"Sales output is keyed on '{forecast.columns[0]}', expected '{AGENT_KEY}'")
    if failures:
        return failures

    leave_ids = set(scores[AGENT_KEY].astype(str))
    sales_ids = set(forecast[AGENT_KEY].astype(str))
    if leave_ids != sales_ids:
        only_leave = len(leave_ids - sales_ids)
        only_sales = len(sales_ids - leave_ids)
        failures.append(
            f"the two outputs cover different rosters: {len(leave_ids)} Leave vs {len(sales_ids)} Sales, "
            f"{only_leave} only in Leave, {only_sales} only in Sales -- they are scored off one snapshot "
            f"and are joined downstream, so they must match exactly"
        )
    else:
        print(f"[check] PASS  both outputs cover the same {len(leave_ids)} agents, keyed on {AGENT_KEY}")

    leave_snap = set(scores["snapshot_date"].astype(str))
    sales_snap = set(forecast["snapshot_date"].astype(str))
    if leave_snap != sales_snap:
        failures.append(f"snapshot mismatch: Leave {sorted(leave_snap)} vs Sales {sorted(sales_snap)}")
    elif len(leave_snap) == 1:
        print(f"[check] PASS  both outputs are off snapshot {next(iter(leave_snap))}")

    return failures


def check_outputs(staging: Path, meta: dict, state: dict) -> tuple[list[str], list[str]]:
    _banner("STEP 3/4  Output checks -- failures block promotion out of staging")
    scores = pd.read_csv(staging / SCORES_FILENAME, dtype={AGENT_KEY: str})
    forecast = pd.read_csv(staging / FORECAST_FILENAME, dtype={AGENT_KEY: str})

    failures, warnings = check_leave(scores, meta, state)
    sales_failures, sales_warnings = check_sales(forecast)
    failures += sales_failures
    warnings += sales_warnings
    failures += check_cross_model(scores, forecast)
    return failures, warnings


# --- Step 4: promote and record -----------------------------------------


def promote(staging: Path) -> list[str]:
    _banner("STEP 4/4  Promote staged outputs and record the run")
    moved = []
    for filename, target_dir in ((SCORES_FILENAME, LEAVE_DIR), (META_FILENAME, LEAVE_DIR),
                                 (FORECAST_FILENAME, SALES_DIR)):
        destination = target_dir / filename
        shutil.copyfile(staging / filename, destination)
        moved.append(str(destination))
        print(f"[promote] {filename} -> {destination}")
    return moved


def record_run(quarter: pd.Timestamp, data_path: Path, meta: dict, staging: Path,
               promoted: list[str], new_clusters: pd.DataFrame, warnings: list[str],
               adopted: bool = False) -> dict:
    scores = pd.read_csv(staging / SCORES_FILENAME, dtype={AGENT_KEY: str})
    shares = scores["risk_tier"].value_counts(normalize=True).sort_index()
    counts = scores["risk_tier"].value_counts().sort_index()

    state = {
        "last_run_utc": _now(),
        "data_quarter": str(quarter.date()),
        "data_file": data_fingerprint(data_path),
        "n_agents": int(len(scores)),
        "base_rate": float(meta["base_rate"]),
        "bias_correction": float(meta["bias_correction"]),
        "corrected_base_rate": float(meta["corrected_base_rate"]),
        "cut_points": [float(c) for c in meta["cut_points"]],
        "tier_counts": {str(t): int(counts.get(t, 0)) for t in (1, 2, 3, 4)},
        "tier_shares": {str(t): float(shares.get(t, 0.0)) for t in (1, 2, 3, 4)},
        "new_tier_b_clusters": int(len(new_clusters)),
        # True when the shipped outputs were CHECKED and recorded rather than
        # produced by this run (--adopt-current). Kept in both the state and
        # the log so a row can never be mistaken for a fit that happened.
        "adopted": bool(adopted),
        "outputs": promoted,
        "warnings": warnings,
        "leave_elapsed_s": meta.get("leave_elapsed_s"),
        "sales_elapsed_s": meta.get("sales_elapsed_s"),
    }
    STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")
    print(f"[record] state -> {STATE_PATH}")

    # The log is the point of the exercise: one row per quarter makes "did the
    # calibration actually move, and by how much" a question answerable by
    # reading a file rather than re-deriving it from old console output.
    row = {
        "run_utc": state["last_run_utc"],
        "data_quarter": state["data_quarter"],
        "n_agents": state["n_agents"],
        "base_rate": state["base_rate"],
        "bias_correction": state["bias_correction"],
        "corrected_base_rate": state["corrected_base_rate"],
        "tier1_share": state["tier_shares"]["1"],
        "tier2_share": state["tier_shares"]["2"],
        "tier3_share": state["tier_shares"]["3"],
        "tier4_share": state["tier_shares"]["4"],
        "new_tier_b_clusters": state["new_tier_b_clusters"],
        "adopted": state["adopted"],
        "n_warnings": len(warnings),
    }
    pd.DataFrame([row]).to_csv(LOG_PATH, mode="a", header=not LOG_PATH.exists(), index=False)
    print(f"[record] appended one row -> {LOG_PATH}")
    return state


def adopt_current(quarter: pd.Timestamp, data_path: Path, state: dict) -> int:
    """Check the ALREADY-SHIPPED outputs and, if they pass, record them as the
    baseline -- without scoring anything.

    This exists because "establish a baseline" and "refit" are different
    requests, and conflating them is expensive here. The Leave model can be
    rerun freely (score-neutral: its pipeline never sorts on the agent key,
    verified 2026-08-30 at max |diff| 0.0 across 27,019 agents). The Sales
    model cannot -- `score_agents.py` sorts on the key and both learners
    subsample by row order, so a rerun with no new data still refits a
    different model and moves every forecast by ~1.5% median. Seeding the
    baseline by refitting would therefore churn 27,019 reviewed numbers to
    record a fact we already know.

    So this verifies rather than regenerates. Everything the gates can say
    about a shipped file, they say here; only the scoring is skipped. The
    recorded state is marked `adopted: true` so the log never implies a fit
    that did not happen.
    """
    _banner("ADOPT CURRENT  Check the shipped outputs and record them as the baseline (no scoring)")
    meta_path = LEAVE_DIR / META_FILENAME
    if not meta_path.exists():
        raise RecalibrationAborted(
            f"{meta_path} is missing, so this quarter's calibration constants are unknown and cannot be "
            f"recorded. Run score_agents.py (or a full recalibration) at least once first."
        )
    meta = json.loads(meta_path.read_text(encoding="utf-8"))

    # The model folders ARE the staging directory in this mode: the files under
    # test are the shipped ones, which is the entire point.
    scores = pd.read_csv(LEAVE_DIR / SCORES_FILENAME, dtype={AGENT_KEY: str})
    forecast = pd.read_csv(SALES_DIR / FORECAST_FILENAME, dtype={AGENT_KEY: str})
    print(f"[adopt] Leave    {LEAVE_DIR / SCORES_FILENAME}  ({len(scores)} rows)")
    print(f"[adopt] Sales    {SALES_DIR / FORECAST_FILENAME}  ({len(forecast)} rows)")

    failures, warnings = check_leave(scores, meta, state)
    sales_failures, sales_warnings = check_sales(forecast)
    failures += sales_failures
    warnings += sales_warnings
    failures += check_cross_model(scores, forecast)

    if failures:
        print()
        for failure in failures:
            print(f"[check] FAIL  {failure}")
        raise RecalibrationAborted(
            f"{len(failures)} check(s) failed against the SHIPPED outputs. These are the files people are "
            f"using right now -- fix them before recording anything as a baseline."
        )
    for warning in warnings:
        print(f"[check] WARN  {warning}")

    promoted = [str(LEAVE_DIR / SCORES_FILENAME), str(SALES_DIR / FORECAST_FILENAME)]
    final = record_run(quarter, data_path, meta, LEAVE_DIR, promoted,
                       pd.DataFrame(), warnings, adopted=True)

    _banner("BASELINE ADOPTED")
    print(f"quarter                  {final['data_quarter']}")
    print(f"agents                   {final['n_agents']}")
    print(f"bias correction          {final['bias_correction']:.4f}x")
    print("Nothing was scored or overwritten. The next run with a new quarter will refit both models.")
    return 0


# --- Orchestration -------------------------------------------------------


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="report whether a recalibration is due, then exit without running anything")
    parser.add_argument("--force", action="store_true",
                        help="recalibrate even if no new quarter has landed")
    parser.add_argument("--dry-run", action="store_true",
                        help="run everything into a temporary directory: nothing promoted, no state or log "
                             "written, existing outputs untouched. Use to rehearse before a quarter lands")
    parser.add_argument("--adopt-current", action="store_true",
                        help="do not score anything: run the output checks against the files ALREADY shipped "
                             "in the model folders and, if they pass, record them as the baseline. Use when "
                             "the current outputs are known-good and you do not want to refit -- notably for "
                             "the Sales model, which is not invariant to a rerun (it sorts on the agent key "
                             "and both learners subsample by row order), so refitting it with no new data "
                             "moves every forecast for no reason a reader could see")
    parser.add_argument("--strict-clusters", action="store_true",
                        help="abort if the catalogue picked up new unverified Tier B mass-mover clusters. "
                             "Off by default because MA's catalogue is generated and has never been "
                             "web-verified, so there is no verification step for a stop to wait on -- see "
                             "the module docstring")
    args = parser.parse_args(argv)

    data_path, mls_code = _leave_constants()
    state = load_state()
    due, reason, quarter = check_due(state, data_path, mls_code)

    _banner("STEP 0/4  Due check")
    print(f"[due] source: {data_path.name}")
    print(f"[due] newest quarter in the data ({mls_code}): {quarter.date()}")
    print(f"[due] {'DUE' if due else 'not due'} -- {reason}")

    if args.check:
        return 0 if due else 1

    if args.adopt_current:
        return adopt_current(quarter, data_path, state)

    if not due and not args.force:
        print("\n[recal] nothing to do. Re-run with --force to recalibrate on the same panel anyway.")
        return 0
    if not due and args.force:
        print("\n[recal] --force given; recalibrating on an unchanged panel.")

    new_clusters, pair_notes = refresh_office_pairs()
    if len(new_clusters) and args.strict_clusters:
        raise RecalibrationAborted(
            f"{len(new_clusters)} new unverified mass-mover cluster(s) and --strict-clusters was given. "
            f"Review them, record any verdict in derive_ma_office_pairs.py, then re-run."
        )

    staging = Path(tempfile.mkdtemp(prefix="ma_recal_"))
    print(f"\n[recal] staging directory: {staging}")
    try:
        meta = run_models(staging)
        failures, warnings = check_outputs(staging, meta, state)

        if failures:
            print()
            for failure in failures:
                print(f"[check] FAIL  {failure}")
            raise RecalibrationAborted(
                f"{len(failures)} output check(s) failed. Staged outputs are in {staging} for inspection "
                f"and were NOT promoted -- the previously shipped files are untouched."
            )
        for warning in warnings:
            print(f"[check] WARN  {warning}")

        if args.dry_run:
            _banner("DRY RUN COMPLETE")
            print(f"Everything ran and every check passed. Outputs are in {staging}, not promoted or recorded.")
            print(f"base rate {meta['base_rate']:.4%} | bias correction {meta['bias_correction']:.4f}x | "
                  f"bias-corrected base rate {meta['corrected_base_rate']:.4%}")
            return 0

        promoted = promote(staging)
        final = record_run(quarter, data_path, meta, staging, promoted, new_clusters, warnings + pair_notes[1:])

        _banner("RECALIBRATION COMPLETE")
        print(f"quarter                  {final['data_quarter']}")
        print(f"agents scored            {final['n_agents']}")
        print(f"base rate                {final['base_rate']:.4%}")
        print(f"bias correction          {final['bias_correction']:.4f}x")
        print(f"bias-corrected base rate {final['corrected_base_rate']:.4%}")
        print(f"tier cut points          {[f'{c:.3%}' for c in final['cut_points']]}")
        print(f"new Tier B clusters      {final['new_tier_b_clusters']}")
        print(f"elapsed                  Leave {final['leave_elapsed_s']:.0f}s, Sales {final['sales_elapsed_s']:.0f}s")
        if warnings:
            print(f"\n{len(warnings)} warning(s) recorded in {STATE_PATH.name} -- review before the scores are used.")
        return 0
    finally:
        if not args.dry_run:
            shutil.rmtree(staging, ignore_errors=True)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except RecalibrationAborted as exc:
        print(f"\n[recal] ABORTED: {exc}", file=sys.stderr)
        sys.exit(2)
